containers :
	$(MAKE) -C shared container
	$(MAKE) -C front container
	$(MAKE) -C angular-frontend container
	$(MAKE) -C base container
	$(MAKE) -C api container
	$(MAKE) -C user container
	$(MAKE) -C user-app container
	$(MAKE) -C user-mfa container
	$(MAKE) -C user-sms container
	$(MAKE) -C user-email container
	$(MAKE) -C auth container
	$(MAKE) -C auth-mfa container
	$(MAKE) -C auth-sms container
	$(MAKE) -C auth-email container
	$(MAKE) -C auth-app container	
	$(MAKE) -C sms container
	$(MAKE) -C repl container
	$(MAKE) -C email container
	$(MAKE) -C generators container
	$(MAKE) -C hashing container
	
	

	

.PHONY : containers